# Generated by Django 4.2.13 on 2024-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
